### ISSUE TITLE
`Warning: Return value of low-level calls not used.`

### ISSUE THREAD

**Issue by Pfed-prog** [TalentLayer/talentlayer-id-contracts#125]
Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:665:13:
    |
665 |             payable(transaction.receiver).call{value: receiverFee}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:686:13:
    |
686 |             payable(transaction.sender).call{value: senderFee}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:806:13:
    |
806 |             payable(transaction.sender).call{value: extraFeeSender}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:814:13:
    |
814 |             payable(transaction.receiver).call{value: extraFeeReceiver}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:843:13:
    |
843 |             sender.call{value: senderFee}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:846:13:
    |
846 |             receiver.call{value: receiverFee}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:856:13:
    |
856 |             sender.call{value: splitFeeAmount}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
   --> contracts/TalentLayerEscrow.sol:857:13:
    |
857 |             receiver.call{value: splitFeeAmount}("");
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning: Return value of low-level calls not used.
    --> contracts/TalentLayerEscrow.sol:1105:13:
     |
1105 |             _recipient.call{value: _amount}("");
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Pfed-prog** [comment]
To fix these `low` level calls - we need to simply remove these lines from contracts saving gas

**Comment by Pfed-prog** [comment]
![image](https://user-images.githubusercontent.com/66903336/219717429-d56dcc42-ce19-4af7-b930-442ba8577e2b.png)

**Comment by Pfed-prog** [comment]
By example: the first warning instance `payable(transaction.receiver).call{value: receiverFee}("");` fixed by
`payable(transaction.receiver).transfer(receiverFee)`

the gas estimation stays the same

**Comment by Pfed-prog** [comment]
Or         
```(bool success, ) = msg.sender.call.value(amount)("");
        require(success, "Transfer failed.");```
solve warning

**Comment by 0xRomain** [comment]
Handle the answer of the call bring some critical issues as now the receiver can break any function using it
