### ISSUE TITLE
gas optimization in modifiers

### ISSUE THREAD

**Issue by Pfed-prog** [TalentLayer/talentlayer-id-contracts#128]
Modifiers code is copied in all instances where it's used, increasing bytecode size. By doing a refractor to the internal function, one can reduce bytecode size significantly at the cost of one JUMP. Consider doing this only if you are constrained by bytecode size.
https://0xmacro.com/blog/solidity-gas-optimizations-cheat-sheet/

**Comment by Pfed-prog** [comment]
```    
    modifier onlyArbitrator() {
        _checkOwner();
        _;
    }

    function _checkOwner() internal view virtual {
        require(msg.sender == address(arbitrator), "Can only be called by the arbitrator.");
    }
```
reduces gas to 768341 in TalentLayerArbitrator

**Comment by 0xRomain** [comment]
Good point, in this case it doesn't change much and reduce code readability, but we can check this point in other case
