### ISSUE TITLE
`mintfee` can not be accessed which will fail mint

### ISSUE THREAD

**Issue by Pfed-prog** [TalentLayer/talentlayer-id-contracts#130]
If the owner of the contract updates the mintfee user does not have a method to query the `mintfee` which fails the mint

contracts/TalentLayerPlatformID.sol

**Comment by 0xRomain** [comment]
What do you mean? mintFee is public

**Comment by Pfed-prog** [comment]
Yes, but there seems to be no function to retrieve the value directly

**Comment by Pfed-prog** [comment]
And if the user calls a contract with more eth than needed will it revert?

**Comment by Pfed-prog** [comment]
I think it's close to https://github.com/code-423n4/2022-11-debtdao-findings/issues/39, imho,

**Comment by 0xRomain** [comment]
Yes it will revert if the user send too much eth
